# Mulitple Campustown Zillow Listings Cleaning

The dataset has been collected through [HasData](https://hasdata.com/), a web scraping service. The dataset contains over 30,000 listings of properties in the Campustowns across the United States.

In [2]:
import pandas as pd
import numpy as np

The `filtered-listings.xlsx` contains result sets using this SQL query:

```sql
SELECT
  property_id,
  date_posted,
  days_on_zillow,
  price,
  last_sold_price,
  description,
  beds,
  baths,
  year_built,
  latitude,
  longitude,
  lot_size,
  living_area,
  address_street,
  address_city,
  address_state,
  address_zipcode,
  address_county,
  address_country,address_raw,
  county_fips,
  reso_is_new_construction,
  reso_architectural_style,
  reso_hoa_fee,
  reso_parking_capacity,
  reso_has_attached_garage
  reso_elementary_school,
  reso_middle_or_junior_school,
  reso_high_school
FROM zillow_properties;
```

In [3]:
df = pd.read_excel("filtered-listings.xlsx")
df

,property_id,date_posted,days_on_zillow,price,last_sold_price,description,beds,baths,year_built,latitude,...,address_country,address_raw,county_fips,reso_is_new_construction,reso_architectural_style,reso_hoa_fee,reso_parking_capacity,reso_elementary_school,reso_middle_or_junior_school,reso_high_school
0,55417927,2025-06-19,245.0,350000,350000,"Charming 2-bed, 1-bath home in Madison?s desir...",2,1.0,1949.0,43.095300,...,USA,105 Harding Street,55025.0,0.0,Bungalow,NaN,1,0.0,Whitehorse,Lafollette
1,55411151,2025-06-23,235.0,615000,615000,One of a kind mid-century modern dream in the ...,4,3.0,1948.0,43.041683,...,USA,1118 WOODLAND Way,55025.0,0.0,Raised Ranch,NaN,2,1.0,Toki,Memorial
2,383203051,2025-05-08,288.0,335000,335000,Charming Ranch Home in Burr Oaks ? Move-In Rea...,3,2.0,1949.0,43.043194,...,USA,849 Dane Street,55025.0,0.0,Ranch,NaN,0,0.0,Call School District,Call School District
3,55409265,2025-07-18,214.0,474500,474500,This is a rare find in the highly sought-after...,2,1.0,1949.0,43.053750,...,USA,4302 Tokay Boulevard,55025.0,0.0,Bungalow,NaN,1,1.0,Hamilton,West
4,55408269,2025-06-01,259.0,585000,585000,"Tucked in the heart of Westmorland, this class...",4,2.0,1948.0,43.055584,...,USA,3815 St Clair Street,55025.0,0.0,Cape Cod,NaN,1,0.0,Cherokee,West
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36464,55402682,2025-07-22,203.0,330000,330000,Ideal location for this cute bungalow in the d...,2,1.0,1949.0,43.073110,...,USA,2833 Barlow Street,55025.0,0.0,Bungalow,NaN,0,0.0,Hamilton,West
36465,55435505,2025-05-19,271.0,425468,425468,Newly remodeled and spacious 3 bedroom 2 bath ...,3,2.0,1949.0,43.121914,...,USA,1713 Vahlen Street,55025.0,0.0,Ranch,NaN,1,0.0,Sherman,East
36466,55407447,2025-05-06,277.0,321000,321000,This charming raised ranch home is ready for y...,3,1.0,1949.0,43.047090,...,USA,1820 Fisher Street,55025.0,0.0,Raised Ranch,NaN,1,1.0,Hamilton,Call School District
36467,55408312,2024-06-20,621.0,539000,539000,Discover the allure of Westmorland Neighborhoo...,4,2.0,1948.0,43.053757,...,USA,596 Park Lane,55025.0,0.0,Raised Ranch,NaN,1,1.0,Hamilton,West
36468,55421505,2024-02-09,739.0,405000,405000,A splash of cape cod charm in the heart of Mad...,4,1.0,1948.0,43.089700,...,USA,510 Dempsey Road,55025.0,0.0,Cape Cod,NaN,1,0.0,Whitehorse,Lafollette

Only filter cities with at least 200 listings. Sometimes, cities that are distant from campustowns are included in the search results, and we want to remove those cities from the dataset. After filtering, we have 28,000 listings in the dataset.

In [7]:
cities_with_at_least_200_listings = (
    df["address_city"]
    .value_counts()
    .to_frame("count")
    .reset_index()
    .query("count > 200")
)
cities_with_at_least_200_listings

       address_city  count
0       Gainesville   5658
1           Madison   5107
2         Lafayette   3114
3         Ann Arbor   3067
4            Athens   2903
5   Charlottesville   2894
6       Chapel Hill   2763
7         Champaign   2325
8         Iowa City   1944
9    West Lafayette   1575
10    State College   1367
11           Urbana   1157
12            Davis    951
13        Middleton    649
14            Savoy    254
15         Carrboro    212

In [ ]:
df = df[
    df["address_city"].isin(cities_with_at_least_200_listings["address_city"])
].copy()
df.shape

(35940, 28)

Write as a parquet file.

In [ ]:
df.to_parquet("campustown_properties.parquet", index=False)